[package]
name = "seaward"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version = "4.3.11", features = ["cargo"]}
reqwest = {version = "0.11", features = ["blocking"]}
scraper = "0.17"
colored = "2.0"
regex = "1.0"
ctrlc = "3.4.0"
tokio = "1.29.1"
