[package]
name = "seaward"
version = "1.0.3"
authors = ["M3nny"]
description = "seaward is a crawler which searches for links or a specified word in a website."
documentation = "https://github.com/M3nny/seaward"
homepage = "https://github.com/M3nny/seaward"
repository = "https://github.com/M3nny/seaward"
keywords = ["cli", "web-crawler", "web-scraping", "rustcrawler"]
categories = ["command-line-utilities"]
license = "MIT"
edition = "2024"

[dependencies]
tokio = {version = "1.45.0", features = ["macros", "rt", "signal", "rt-multi-thread"]}
clap = {version = "4.5.38", features = ["cargo", "derive"]}
reqwest = {version = "0.12.5"}
regex = {version = "1.11.1"}
scraper = {version = "0.23.1", default-features = false}
colored = {version = "3.0.0", default-features = false}
fastbloom = {version = "0.11.0", default-features = false}
rayon = {version = "1.10", default-features = false}
tokio-util = {version = "0.7.15", default-features = false}

# use 'cargo build'
# for the development unoptimized build
[profile.dev]
panic = "unwind"   # clean the stack on panic and produce a backtrace
incremental = true # enable incremental build


# use 'cargo build --release --no-default-features'
# for the optimized release build
[profile.release]
panic = "unwind"    # clean the stack on panic and produce a backtrace
incremental = false # build from scratch every time
strip = true        # strip symbols from the binary
lto = true          # link time optimizations (remove dead code)
codegen-units = 1   # use a single code generation unit
